/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dgmpp;

public class Attribute {
  private long swigCPtr;
  private boolean swigCMemOwn;

  protected Attribute(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Attribute obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_Attribute(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int getAttributeID() {
    return dgmppJNI.Attribute_getAttributeID(swigCPtr, this);
  }

  public boolean isFakeAttribute() {
    return dgmppJNI.Attribute_isFakeAttribute(swigCPtr, this);
  }

  public float getValue() {
    return dgmppJNI.Attribute_getValue(swigCPtr, this);
  }

  public float getInitialValue() {
    return dgmppJNI.Attribute_getInitialValue(swigCPtr, this);
  }

  public boolean isStackable() {
    return dgmppJNI.Attribute_isStackable(swigCPtr, this);
  }

  public boolean highIsGood() {
    return dgmppJNI.Attribute_highIsGood(swigCPtr, this);
  }

  public void setValue(float value) {
    dgmppJNI.Attribute_setValue(swigCPtr, this, value);
  }

  public float dec(float value) {
    return dgmppJNI.Attribute_dec(swigCPtr, this, value);
  }

  public float inc(float value) {
    return dgmppJNI.Attribute_inc(swigCPtr, this, value);
  }

  public String getAttributeName() {
    return dgmppJNI.Attribute_getAttributeName(swigCPtr, this);
  }

}
