/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dgmpp;

public class CharactersList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CharactersList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CharactersList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_CharactersList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CharactersList() {
    this(dgmppJNI.new_CharactersList(), true);
  }

  public long size() {
    return dgmppJNI.CharactersList_size(swigCPtr, this);
  }

  public boolean isEmpty() {
    return dgmppJNI.CharactersList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    dgmppJNI.CharactersList_clear(swigCPtr, this);
  }

  public void add(Character x) {
    dgmppJNI.CharactersList_add(swigCPtr, this, Character.getCPtr(x), x);
  }

  public Character get(int i) {
    long cPtr = dgmppJNI.CharactersList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Character(cPtr, true);
  }

}
