/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dgmpp;

public class DamagePattern {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DamagePattern(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DamagePattern obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_DamagePattern(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DamagePattern() {
    this(dgmppJNI.new_DamagePattern__SWIG_0(), true);
  }

  public DamagePattern(float em, float thermal, float kinetic, float explosive) {
    this(dgmppJNI.new_DamagePattern__SWIG_1(em, thermal, kinetic, explosive), true);
  }

  public HitPoints effectiveHitPoints(Resistances resistances, HitPoints hitPoints) {
    return new HitPoints(dgmppJNI.DamagePattern_effectiveHitPoints(swigCPtr, this, Resistances.getCPtr(resistances), resistances, HitPoints.getCPtr(hitPoints), hitPoints), true);
  }

  public Tank effectiveTank(Resistances resistances, Tank tank) {
    return new Tank(dgmppJNI.DamagePattern_effectiveTank(swigCPtr, this, Resistances.getCPtr(resistances), resistances, Tank.getCPtr(tank), tank), true);
  }

}
