/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dgmpp;

public class DamageVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DamageVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DamageVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_DamageVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DamageVector(float value) {
    this(dgmppJNI.new_DamageVector__SWIG_0(value), true);
  }

  public DamageVector() {
    this(dgmppJNI.new_DamageVector__SWIG_1(), true);
  }

  public DamageVector(float em, float thermal, float kinetic, float explosive) {
    this(dgmppJNI.new_DamageVector__SWIG_2(em, thermal, kinetic, explosive), true);
  }

  public DamageVector effectiveDamage(ResistancesLayer resistances) {
    return new DamageVector(dgmppJNI.DamageVector_effectiveDamage(swigCPtr, this, ResistancesLayer.getCPtr(resistances), resistances), true);
  }

  public float getFloat() {
    return dgmppJNI.DamageVector_getFloat(swigCPtr, this);
  }

}
