/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dgmpp;

public class HostileTarget {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected HostileTarget(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HostileTarget obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_HostileTarget(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public HostileTarget(float range, float angularVelocity, float signature, float velocity) {
    this(dgmppJNI.new_HostileTarget__SWIG_0(range, angularVelocity, signature, velocity), true);
  }

  public HostileTarget(float range, float angularVelocity, float signature) {
    this(dgmppJNI.new_HostileTarget__SWIG_1(range, angularVelocity, signature), true);
  }

  public HostileTarget(float range, float angularVelocity) {
    this(dgmppJNI.new_HostileTarget__SWIG_2(range, angularVelocity), true);
  }

  public HostileTarget(float range) {
    this(dgmppJNI.new_HostileTarget__SWIG_3(range), true);
  }

  public HostileTarget() {
    this(dgmppJNI.new_HostileTarget__SWIG_4(), true);
  }

  public void setAngularVelocity(float value) {
    dgmppJNI.HostileTarget_angularVelocity_set(swigCPtr, this, value);
  }

  public float getAngularVelocity() {
    return dgmppJNI.HostileTarget_angularVelocity_get(swigCPtr, this);
  }

  public void setVelocity(float value) {
    dgmppJNI.HostileTarget_velocity_set(swigCPtr, this, value);
  }

  public float getVelocity() {
    return dgmppJNI.HostileTarget_velocity_get(swigCPtr, this);
  }

  public void setSignature(float value) {
    dgmppJNI.HostileTarget_signature_set(swigCPtr, this, value);
  }

  public float getSignature() {
    return dgmppJNI.HostileTarget_signature_get(swigCPtr, this);
  }

  public void setRange(float value) {
    dgmppJNI.HostileTarget_range_set(swigCPtr, this, value);
  }

  public float getRange() {
    return dgmppJNI.HostileTarget_range_get(swigCPtr, this);
  }

}
