/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dgmpp;

public class Ship extends Item {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected Ship(long cPtr, boolean cMemoryOwn) {
    super(dgmppJNI.Ship_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Ship obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        dgmppJNI.delete_Ship(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Module addModule(int typeID, boolean forced) {
    long cPtr = dgmppJNI.Ship_addModule__SWIG_0(swigCPtr, this, typeID, forced);
    return (cPtr == 0) ? null : new Module(cPtr, true);
  }

  public Module addModule(int typeID) {
    long cPtr = dgmppJNI.Ship_addModule__SWIG_1(swigCPtr, this, typeID);
    return (cPtr == 0) ? null : new Module(cPtr, true);
  }

  public Module replaceModule(Module oldModule, int typeID) {
    long cPtr = dgmppJNI.Ship_replaceModule(swigCPtr, this, Module.getCPtr(oldModule), oldModule, typeID);
    return (cPtr == 0) ? null : new Module(cPtr, true);
  }

  public void removeModule(Module module) {
    dgmppJNI.Ship_removeModule(swigCPtr, this, Module.getCPtr(module), module);
  }

  public Drone addDrone(int typeID) {
    long cPtr = dgmppJNI.Ship_addDrone(swigCPtr, this, typeID);
    return (cPtr == 0) ? null : new Drone(cPtr, true);
  }

  public void removeDrone(Drone drone) {
    dgmppJNI.Ship_removeDrone(swigCPtr, this, Drone.getCPtr(drone), drone);
  }

  public ModulesList getModules() {
    return new ModulesList(dgmppJNI.Ship_getModules(swigCPtr, this), false);
  }

  public DronesList getDrones() {
    return new DronesList(dgmppJNI.Ship_getDrones(swigCPtr, this), false);
  }

  public boolean canFit(Module module) {
    return dgmppJNI.Ship_canFit(swigCPtr, this, Module.getCPtr(module), module);
  }

  public boolean isDisallowedAssistance() {
    return dgmppJNI.Ship_isDisallowedAssistance(swigCPtr, this);
  }

  public boolean isDisallowedOffensiveModifiers() {
    return dgmppJNI.Ship_isDisallowedOffensiveModifiers(swigCPtr, this);
  }

  public void reset() {
    dgmppJNI.Ship_reset(swigCPtr, this);
  }

  public void addEffects(Effect.Category category) {
    dgmppJNI.Ship_addEffects(swigCPtr, this, category.swigValue());
  }

  public void removeEffects(Effect.Category category) {
    dgmppJNI.Ship_removeEffects(swigCPtr, this, category.swigValue());
  }

  public void addProjectedModule(Module module) {
    dgmppJNI.Ship_addProjectedModule(swigCPtr, this, Module.getCPtr(module), module);
  }

  public void removeProjectedModule(Module module) {
    dgmppJNI.Ship_removeProjectedModule(swigCPtr, this, Module.getCPtr(module), module);
  }

  public void addProjectedDrone(Drone drone) {
    dgmppJNI.Ship_addProjectedDrone(swigCPtr, this, Drone.getCPtr(drone), drone);
  }

  public void removeProjectedDrone(Drone drone) {
    dgmppJNI.Ship_removeProjectedDrone(swigCPtr, this, Drone.getCPtr(drone), drone);
  }

  public DamagePattern getDamagePattern() {
    return new DamagePattern(dgmppJNI.Ship_getDamagePattern(swigCPtr, this), false);
  }

  public void setDamagePattern(DamagePattern damagePattern) {
    dgmppJNI.Ship_setDamagePattern(swigCPtr, this, DamagePattern.getCPtr(damagePattern), damagePattern);
  }

  public int getNumberOfSlots(Module.Slot slot) {
    return dgmppJNI.Ship_getNumberOfSlots(swigCPtr, this, slot.swigValue());
  }

  public int getFreeSlots(Module.Slot slot) {
    return dgmppJNI.Ship_getFreeSlots(swigCPtr, this, slot.swigValue());
  }

  public int getUsedSlots(Module.Slot slot) {
    return dgmppJNI.Ship_getUsedSlots(swigCPtr, this, slot.swigValue());
  }

  public int getNumberOfHardpoints(Module.Hardpoint hardpoint) {
    return dgmppJNI.Ship_getNumberOfHardpoints(swigCPtr, this, hardpoint.swigValue());
  }

  public int getFreeHardpoints(Module.Hardpoint hardpoint) {
    return dgmppJNI.Ship_getFreeHardpoints(swigCPtr, this, hardpoint.swigValue());
  }

  public int getUsedHardpoints(Module.Hardpoint hardpoint) {
    return dgmppJNI.Ship_getUsedHardpoints(swigCPtr, this, hardpoint.swigValue());
  }

  public float getCalibrationUsed() {
    return dgmppJNI.Ship_getCalibrationUsed(swigCPtr, this);
  }

  public float getTotalCalibration() {
    return dgmppJNI.Ship_getTotalCalibration(swigCPtr, this);
  }

  public float getPowerGridUsed() {
    return dgmppJNI.Ship_getPowerGridUsed(swigCPtr, this);
  }

  public float getTotalPowerGrid() {
    return dgmppJNI.Ship_getTotalPowerGrid(swigCPtr, this);
  }

  public float getCpuUsed() {
    return dgmppJNI.Ship_getCpuUsed(swigCPtr, this);
  }

  public float getTotalCpu() {
    return dgmppJNI.Ship_getTotalCpu(swigCPtr, this);
  }

  public float getDroneBandwidthUsed() {
    return dgmppJNI.Ship_getDroneBandwidthUsed(swigCPtr, this);
  }

  public float getTotalDroneBandwidth() {
    return dgmppJNI.Ship_getTotalDroneBandwidth(swigCPtr, this);
  }

  public float getDroneBayUsed() {
    return dgmppJNI.Ship_getDroneBayUsed(swigCPtr, this);
  }

  public float getTotalDroneBay() {
    return dgmppJNI.Ship_getTotalDroneBay(swigCPtr, this);
  }

  public float getCapCapacity() {
    return dgmppJNI.Ship_getCapCapacity(swigCPtr, this);
  }

  public boolean isCapStable() {
    return dgmppJNI.Ship_isCapStable(swigCPtr, this);
  }

  public float getCapLastsTime() {
    return dgmppJNI.Ship_getCapLastsTime(swigCPtr, this);
  }

  public float getCapStableLevel() {
    return dgmppJNI.Ship_getCapStableLevel(swigCPtr, this);
  }

  public float getCapUsed() {
    return dgmppJNI.Ship_getCapUsed(swigCPtr, this);
  }

  public float getCapRecharge() {
    return dgmppJNI.Ship_getCapRecharge(swigCPtr, this);
  }

  public Resistances getResistances() {
    return new Resistances(dgmppJNI.Ship_getResistances(swigCPtr, this), false);
  }

  public Tank getTank() {
    return new Tank(dgmppJNI.Ship_getTank(swigCPtr, this), false);
  }

  public Tank getEffectiveTank() {
    return new Tank(dgmppJNI.Ship_getEffectiveTank(swigCPtr, this), false);
  }

  public Tank getSustainableTank() {
    return new Tank(dgmppJNI.Ship_getSustainableTank(swigCPtr, this), false);
  }

  public Tank getEffectiveSustainableTank() {
    return new Tank(dgmppJNI.Ship_getEffectiveSustainableTank(swigCPtr, this), false);
  }

  public HitPoints getHitPoints() {
    return new HitPoints(dgmppJNI.Ship_getHitPoints(swigCPtr, this), false);
  }

  public HitPoints getEffectiveHitPoints() {
    return new HitPoints(dgmppJNI.Ship_getEffectiveHitPoints(swigCPtr, this), false);
  }

  public float getShieldRecharge() {
    return dgmppJNI.Ship_getShieldRecharge(swigCPtr, this);
  }

  public DamageVector getWeaponDps(HostileTarget target) {
    return new DamageVector(dgmppJNI.Ship_getWeaponDps__SWIG_0(swigCPtr, this, HostileTarget.getCPtr(target), target), true);
  }

  public DamageVector getWeaponDps() {
    return new DamageVector(dgmppJNI.Ship_getWeaponDps__SWIG_1(swigCPtr, this), true);
  }

  public DamageVector getWeaponVolley() {
    return new DamageVector(dgmppJNI.Ship_getWeaponVolley(swigCPtr, this), true);
  }

  public DamageVector getDroneDps(HostileTarget target) {
    return new DamageVector(dgmppJNI.Ship_getDroneDps__SWIG_0(swigCPtr, this, HostileTarget.getCPtr(target), target), true);
  }

  public DamageVector getDroneDps() {
    return new DamageVector(dgmppJNI.Ship_getDroneDps__SWIG_1(swigCPtr, this), true);
  }

  public DamageVector getDroneVolley() {
    return new DamageVector(dgmppJNI.Ship_getDroneVolley(swigCPtr, this), true);
  }

  public float getAlignTime() {
    return dgmppJNI.Ship_getAlignTime(swigCPtr, this);
  }

  public float getWarpSpeed() {
    return dgmppJNI.Ship_getWarpSpeed(swigCPtr, this);
  }

  public float getMaxWarpDistance() {
    return dgmppJNI.Ship_getMaxWarpDistance(swigCPtr, this);
  }

  public float getVelocity() {
    return dgmppJNI.Ship_getVelocity(swigCPtr, this);
  }

  public float getSignatureRadius() {
    return dgmppJNI.Ship_getSignatureRadius(swigCPtr, this);
  }

  public float getMass() {
    return dgmppJNI.Ship_getMass(swigCPtr, this);
  }

  public float getVolume() {
    return dgmppJNI.Ship_getVolume(swigCPtr, this);
  }

  public float getAgility() {
    return dgmppJNI.Ship_getAgility(swigCPtr, this);
  }

  public float getMaxVelocityInOrbit(float r) {
    return dgmppJNI.Ship_getMaxVelocityInOrbit(swigCPtr, this, r);
  }

  public float getOrbitRadiusWithTransverseVelocity(float v) {
    return dgmppJNI.Ship_getOrbitRadiusWithTransverseVelocity(swigCPtr, this, v);
  }

  public float getOrbitRadiusWithAngularVelocity(float v) {
    return dgmppJNI.Ship_getOrbitRadiusWithAngularVelocity(swigCPtr, this, v);
  }

  public int getMaxTargets() {
    return dgmppJNI.Ship_getMaxTargets(swigCPtr, this);
  }

  public float getMaxTargetRange() {
    return dgmppJNI.Ship_getMaxTargetRange(swigCPtr, this);
  }

  public float getScanStrength() {
    return dgmppJNI.Ship_getScanStrength(swigCPtr, this);
  }

  public Ship.ScanType getScanType() {
    return Ship.ScanType.swigToEnum(dgmppJNI.Ship_getScanType(swigCPtr, this));
  }

  public float getProbeSize() {
    return dgmppJNI.Ship_getProbeSize(swigCPtr, this);
  }

  public float getScanResolution() {
    return dgmppJNI.Ship_getScanResolution(swigCPtr, this);
  }

  public int getMaxActiveDrones() {
    return dgmppJNI.Ship_getMaxActiveDrones(swigCPtr, this);
  }

  public int getActiveDrones() {
    return dgmppJNI.Ship_getActiveDrones(swigCPtr, this);
  }

  public void updateHeatDamage() {
    dgmppJNI.Ship_updateHeatDamage(swigCPtr, this);
  }

  public final static class ScanType {
    public final static Ship.ScanType SCAN_TYPE_RADAR = new Ship.ScanType("SCAN_TYPE_RADAR");
    public final static Ship.ScanType SCAN_TYPE_LADAR = new Ship.ScanType("SCAN_TYPE_LADAR");
    public final static Ship.ScanType SCAN_TYPE_MAGNETOMETRIC = new Ship.ScanType("SCAN_TYPE_MAGNETOMETRIC");
    public final static Ship.ScanType SCAN_TYPE_GRAVIMETRIC = new Ship.ScanType("SCAN_TYPE_GRAVIMETRIC");
    public final static Ship.ScanType SCAN_TYPE_MULTISPECTRAL = new Ship.ScanType("SCAN_TYPE_MULTISPECTRAL");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static ScanType swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + ScanType.class + " with value " + swigValue);
    }

    private ScanType(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private ScanType(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private ScanType(String swigName, ScanType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static ScanType[] swigValues = { SCAN_TYPE_RADAR, SCAN_TYPE_LADAR, SCAN_TYPE_MAGNETOMETRIC, SCAN_TYPE_GRAVIMETRIC, SCAN_TYPE_MULTISPECTRAL };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
