/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dgmpp;

public class StructuresList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected StructuresList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StructuresList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_StructuresList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StructuresList() {
    this(dgmppJNI.new_StructuresList(), true);
  }

  public long size() {
    return dgmppJNI.StructuresList_size(swigCPtr, this);
  }

  public boolean isEmpty() {
    return dgmppJNI.StructuresList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    dgmppJNI.StructuresList_clear(swigCPtr, this);
  }

  public void add(Structure x) {
    dgmppJNI.StructuresList_add(swigCPtr, this, Structure.getCPtr(x), x);
  }

  public Structure get(int i) {
    long cPtr = dgmppJNI.StructuresList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Structure(cPtr, true);
  }

}
