/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dgmpp;

public class Structure extends Module {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected Structure(long cPtr, boolean cMemoryOwn) {
    super(dgmppJNI.Structure_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Structure obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        dgmppJNI.delete_Structure(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Resistances getResistances() {
    return new Resistances(dgmppJNI.Structure_getResistances(swigCPtr, this), false);
  }

  public Tank getTank() {
    return new Tank(dgmppJNI.Structure_getTank(swigCPtr, this), false);
  }

  public Tank getEffectiveTank() {
    return new Tank(dgmppJNI.Structure_getEffectiveTank(swigCPtr, this), false);
  }

  public HitPoints getHitPoints() {
    return new HitPoints(dgmppJNI.Structure_getHitPoints(swigCPtr, this), false);
  }

  public HitPoints getEffectiveHitPoints() {
    return new HitPoints(dgmppJNI.Structure_getEffectiveHitPoints(swigCPtr, this), false);
  }

  public float getShieldRecharge() {
    return dgmppJNI.Structure_getShieldRecharge(swigCPtr, this);
  }

}
